/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AMH
 */
public class Pations extends javax.swing.JFrame {

    DefaultTableModel dtm;
    Connection con;
    ArrayList<Integer> patientId = new ArrayList<>();


    /**
     * Creates new form Doctor
     */
    public Pations() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        dtm = new DefaultTableModel();
        
        dtm.addColumn("patient name");
        dtm.addColumn("patient age");
        dtm.addColumn("patient gender");
        dtm.addColumn("patient status");
        
                try {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3333/work","root","root");
             //JOptionPane.showMessageDialog(this, "goood");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Connection faild " + ex);
        }
        
        filltablemodel();


    }
    
            private void filltablemodel(){
        try {
            
            dtm.setRowCount(0);
            PreparedStatement stmt = con.prepareStatement("select * from patients");
            
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
                
                patientId.add(rs.getInt(1));
                dtm.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                
            }
           tbl.setModel(dtm);
            
        } catch (SQLException ex) {
            Logger.getLogger(Doctors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        edit = new javax.swing.JButton();
        add = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setWheelScrollingEnabled(false);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 460, 520));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Age :");
        jLabel2.setAlignmentX(0.5F);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 181, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jLabel3.setAlignmentX(0.5F);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 181, 32));

        gender.add(male);
        male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setSelected(true);
        male.setText("Male");
        male.setAlignmentX(0.5F);
        male.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 41));

        gender.add(female);
        female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, 41));

        edit.setBackground(new java.awt.Color(0, 204, 0));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edit.setText("Edite");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 233, -1));

        add.setBackground(new java.awt.Color(51, 0, 153));
        add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 233, -1));

        del.setBackground(new java.awt.Color(204, 0, 0));
        del.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel2.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 233, -1));

        jButton5.setBackground(new java.awt.Color(0, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("Home Page >>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, 48));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMH\\Downloads\\pngwing.com (10).png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, -1));

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane2.setViewportView(txtarea);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 220, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("status :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        new Home_Page().setVisible(true);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
        if(!name.getText().isEmpty() && !age.getText().isEmpty() && !txtarea.getText().isEmpty()){
            try {
                String txt_Name = name.getText();
                double txt_age = Double.parseDouble(age.getText());
                String gender;
                if (male.isSelected()) {
                    gender = "Male";
                } else {
                    gender = "Female";
                }
                
                
                String txt_area = txtarea.getText();
                
                
                PreparedStatement stmt = con.prepareStatement("insert into patients(name,age,gender,patients_status) VALUES (?,?,?,?)");
                
                stmt.setString(1, txt_Name);
                stmt.setDouble(2, txt_age);
                stmt.setString(3, gender);
                stmt.setString(4, txt_area);
                
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Patient Add Successfully");
                filltablemodel();

            } catch (SQLException ex) {
                Logger.getLogger(Pations.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_addActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        try {
            PreparedStatement stmt = con.prepareStatement("delete from patients where patient_id=?");
            
            stmt.setInt(1, patientId.get(tbl.getSelectedRow()));
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Patient Deleted Successfully");
            filltablemodel();
        } catch (SQLException ex) {
            Logger.getLogger(Pations.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_delActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        if(!name.getText().isEmpty() && !age.getText().isEmpty() && !txtarea.getText().isEmpty()){
            try {
                String txt_Name = name.getText();
                double txt_age = Double.parseDouble(age.getText());
                String gender;
                if (male.isSelected()) {
                    gender = "Male";
                } else {
                    gender = "Female";
                }
                
                
                String txt_area = txtarea.getText();
                
                
                PreparedStatement stmt = con.prepareStatement("update patients set name=?,age=?,gender=?,patients_status=? where patient_id=?");
                
                stmt.setString(1, txt_Name);
                stmt.setDouble(2, txt_age);
                stmt.setString(3, gender);
                stmt.setString(4, txt_area);
                stmt.setInt(5, patientId.get(tbl.getSelectedRow()));

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Patient Updated Successfully");
                filltablemodel();
            } catch (SQLException ex) {
                Logger.getLogger(Pations.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_editActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        name.setText(tbl.getValueAt(tbl.getSelectedRow(), 0).toString());
        age.setText(tbl.getValueAt(tbl.getSelectedRow(), 1).toString());
        
        if(tbl.getValueAt(tbl.getSelectedRow(), 2).toString().equals("Female"))
            female.setSelected(true);
        else
            male.setSelected(true);
        
        txtarea.setText(tbl.getValueAt(tbl.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField age;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTable tbl;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
